create database cellphone;

CREATE TABLE `CELLPHONE_BRAND` (
	`CELLPHONE_ID` int(3) NOT NULL AUTO_INCREMENT,
	`CELLPHONE_BRAND` varchar(45) NOT NULL,
	PRIMARY KEY (`CELLPHONE_ID`)
);
 
CREATE TABLE `CELLPHONE_MODEL` (
	`MODEL_ID` int(11) NOT NULL AUTO_INCREMENT,
	`MODEL_NAME` varchar(128) NOT NULL,
	`MODEL_COLOR` varchar(10) NOT NULL,
	`MODEL_SCREEN_SIZE` float(3,1) NOT NULL,
	`MODEL_TYPE` varchar(10) NOT NULL,
	`MODEL_OS` varchar(20) NOT NULL,
	`MODEL_PROCESSOR` varchar(50) NOT NULL,
	`MODEL_RAM` int(6) NOT NULL,
	`MODEL_INTERNAL_MEMORY` int(6) NOT NULL,
	`MODEL_LENGTH` float(3,1) NOT NULL,
	`MODEL_BREADTH` float(3,1) NOT NULL,
	`MODEL_THICKNESS` float(3,1) NOT NULL,
	`MODEL_RELEASE_DATE` date NOT NULL,
    `CELLPHONE_ID` int(3) NOT NULL,
	PRIMARY KEY (`MODEL_ID`),
	KEY `CELLPHONE_FK` (`CELLPHONE_ID`),
	CONSTRAINT `CELLPHONE_FK` FOREIGN KEY (`CELLPHONE_ID`) REFERENCES `CELLPHONE_BRAND` (`CELLPHONE_ID`)
);

CREATE TABLE `USER_LOGIN` (
	`username` varchar(100) NOT NULL,
	`password` varchar(45) NOT NULL,
	`enabled` char(1) NOT NULL
);

CREATE TABLE `USER_ROLE` (
	`username` varchar(100) NOT NULL,
	`role` varchar(45) NOT NULL
);

insert into USER_LOGIN values("navneet","nvnt8891",'y');
insert into USER_ROLE values("navneet","admin");